import { type Subject, type Question } from '@/types';

export const MOCK_SUBJECTS: Subject[] = [
  {
    id: 'a1000000-0000-0000-0000-000000000001',
    department: ['CS', 'IT', 'AL', 'AD', 'EEE', 'EIE', 'ME', 'MZ', 'AG', 'BT'],
    subject_name: 'Engineering Mathematics II',
    icon: '∑',
  },
  {
    id: 'a1000000-0000-0000-0000-000000000002',
    department: ['CS', 'IT', 'AL', 'AD', 'EEE', 'EIE', 'ME', 'MZ', 'AG', 'BT'],
    subject_name: 'Electromagnetism and Modern Physics',
    icon: '⚛',
  },
  {
    id: 'a1000000-0000-0000-0000-000000000003',
    department: ['CS', 'IT', 'AL', 'AD', 'EEE', 'EIE', 'ME', 'MZ', 'AG', 'BT'],
    subject_name: 'Engineering Chemistry II',
    icon: '🧪',
  },
  {
    id: 'a1000000-0000-0000-0000-000000000004',
    department: ['CS', 'IT', 'AL', 'AD', 'EEE', 'EIE', 'ME', 'MZ', 'AG', 'BT'],
    subject_name: 'Computational Problem Solving',
    icon: '<>',
  },
  {
    id: 'a1000000-0000-0000-0000-000000000005',
    department: ['CS', 'IT', 'AL', 'AD'],
    subject_name: 'Digital Computer Electronics',
    icon: '🖥',
  },
  {
    id: 'a1000000-0000-0000-0000-000000000006',
    department: ['CS', 'IT', 'AL', 'AD', 'AG', 'BT'],
    subject_name: 'Tamils and Technology',
    icon: '🏛',
  },
  {
    id: 'a1000000-0000-0000-0000-000000000007',
    department: [],
    subject_name: 'Basics of Electrical Engineering',
    icon: '⚡',
  },
  {
    id: 'a1000000-0000-0000-0000-000000000008',
    department: ['EEE', 'EIE', 'ME', 'MZ', 'AG', 'BT'],
    subject_name: 'Basics of Electronics Engineering',
    icon: '🔌',
  },
];

export const MOCK_QUESTIONS: Question[] = [
  // Engineering Mathematics II
  {
    id: 'q1-1',
    subject_id: 'a1000000-0000-0000-0000-000000000001',
    question: 'Define the Laplace Transform and state its linearity property.',
    answer: 'The Laplace Transform of a function f(t), defined for t ≥ 0, is given by L{f(t)} = F(s) = ∫₀^∞ e^(-st) f(t) dt, where s is a complex number. The linearity property states that L{af(t) + bg(t)} = aF(s) + bG(s), where a and b are constants.',
    image_url: null,
    references: 'Advanced Engineering Mathematics, 10th Edition',
    notes: 'Important for solving differential equations.',
    order_index: 1,
  },
  {
    id: 'q1-2',
    subject_id: 'a1000000-0000-0000-0000-000000000001',
    question: 'Find the Laplace Transform of e^(at) and sin(bt).',
    answer: 'L{e^(at)} = 1/(s-a) for s > a. L{sin(bt)} = b/(s² + b²) for s > 0. These are fundamental transforms used extensively in solving differential equations.',
    image_url: null,
    references: 'Thomas Calculus, Chapter 15',
    notes: 'Remember the convergence conditions.',
    order_index: 2,
  },
  {
    id: 'q1-3',
    subject_id: 'a1000000-0000-0000-0000-000000000001',
    question: 'State and prove the First Shifting Theorem.',
    answer: 'First Shifting Theorem: If L{f(t)} = F(s), then L{e^(at)f(t)} = F(s-a). Proof: L{e^(at)f(t)} = ∫₀^∞ e^(-st) e^(at) f(t) dt = ∫₀^∞ e^(-(s-a)t) f(t) dt = F(s-a).',
    image_url: null,
    references: 'Kreyszig, Advanced Engineering Mathematics',
    notes: 'A standard proof in exams.',
    order_index: 3,
  },
  {
    id: 'q1-4',
    subject_id: 'a1000000-0000-0000-0000-000000000001',
    question: 'Explain Inverse Laplace Transform with examples.',
    answer: 'The Inverse Laplace Transform recovers f(t) from F(s): L⁻¹{F(s)} = f(t). Examples: L⁻¹{1/(s-a)} = e^(at), L⁻¹{b/(s²+b²)} = sin(bt), L⁻¹{s/(s²+b²)} = cos(bt).',
    image_url: null,
    references: 'Standard Math Tables',
    notes: 'Partial fraction decomposition is often required.',
    order_index: 4,
  },
  {
    id: 'q1-5',
    subject_id: 'a1000000-0000-0000-0000-000000000001',
    question: 'Solve the differential equation y\'\' + 4y = sin(2t) using Laplace Transform.',
    answer: 'Taking Laplace Transform: s²Y(s) - sy(0) - y\'(0) + 4Y(s) = 2/(s²+4). With y(0)=0, y\'(0)=0: Y(s)(s²+4) = 2/(s²+4), so Y(s) = 2/(s²+4)². Using convolution or partial fractions: y(t) = (1/4)(sin(2t) - 2t·cos(2t)).',
    image_url: null,
    references: 'Differential Equations Handbook',
    notes: 'Resonance condition because s²+4 matches the frequency.',
    order_index: 5,
  },

  // Electromagnetism and Modern Physics
  {
    id: 'q2-1',
    subject_id: 'a1000000-0000-0000-0000-000000000002',
    question: 'State Gauss\'s Law and derive the electric field due to an infinite plane sheet of charge.',
    answer: 'Gauss\'s Law: ∮ E⃗·dA⃗ = Q_enc/ε₀. For an infinite plane sheet with surface charge density σ, using a cylindrical Gaussian surface: 2EA = σA/ε₀, giving E = σ/(2ε₀) directed perpendicular to the surface.',
    image_url: null,
    references: 'Introduction to Electrodynamics, Griffiths',
    notes: 'Field is independent of distance from the sheet.',
    order_index: 1,
  },
  {
    id: 'q2-2',
    subject_id: 'a1000000-0000-0000-0000-000000000002',
    question: 'Explain Faraday\'s Law of electromagnetic induction.',
    answer: 'Faraday\'s Law states that the induced EMF in a closed circuit is equal to the negative rate of change of magnetic flux through the circuit: EMF = -dΦ_B/dt, where Φ_B = ∫ B⃗·dA⃗. This is the basis of electromagnetic induction.',
    image_url: null,
    references: 'Physics for Scientists and Engineers, Serway',
    notes: 'Lenz\'s Law gives the negative sign (conservation of energy).',
    order_index: 2,
  },
  {
    id: 'q2-3',
    subject_id: 'a1000000-0000-0000-0000-000000000002',
    question: 'Derive the de Broglie wavelength and explain wave-particle duality.',
    answer: 'de Broglie proposed that matter has wave properties: λ = h/p = h/(mv), where h is Planck\'s constant. Wave-particle duality means that all matter exhibits both wave and particle properties. For electrons: λ = h/√(2mE_k).',
    image_url: null,
    references: 'Concepts of Modern Physics, Beiser',
    notes: 'Confirmed by Davisson-Germer experiment.',
    order_index: 3,
  },
  {
    id: 'q2-4',
    subject_id: 'a1000000-0000-0000-0000-000000000002',
    question: 'Explain the photoelectric effect and Einstein\'s equation.',
    answer: 'When light strikes a metal surface, electrons are emitted if the frequency exceeds a threshold. Einstein\'s equation: E_k(max) = hν - φ, where hν is photon energy and φ is the work function. This proved the quantum nature of light.',
    image_url: null,
    references: 'Modern Physics, Krane',
    notes: 'Intensity affects photocurrent, frequency affects electron energy.',
    order_index: 4,
  },
  {
    id: 'q2-5',
    subject_id: 'a1000000-0000-0000-0000-000000000002',
    question: 'Describe Maxwell\'s equations in differential form.',
    answer: '1. ∇·E⃗ = ρ/ε₀ (Gauss), 2. ∇·B⃗ = 0 (No monopoles), 3. ∇×E⃗ = -∂B⃗/∂t (Faraday), 4. ∇×B⃗ = μ₀J⃗ + μ₀ε₀∂E⃗/∂t (Ampère-Maxwell). These four equations completely describe classical electromagnetism.',
    image_url: null,
    references: 'Griffiths, Chapter 7',
    notes: 'Unified electricity and magnetism into a single theory.',
    order_index: 5,
  },

  // Engineering Chemistry II
  {
    id: 'q3-1',
    subject_id: 'a1000000-0000-0000-0000-000000000003',
    question: 'Explain the mechanism of electrochemical corrosion.',
    answer: 'Electrochemical corrosion involves the formation of galvanic cells on the metal surface. At the anode: M → M^n+ + ne⁻ (oxidation/dissolution). At the cathode: O₂ + 2H₂O + 4e⁻ → 4OH⁻ (in neutral/alkaline) or 2H⁺ + 2e⁻ → H₂ (in acidic). The metal acts as both anode and cathode.',
    image_url: null,
    references: 'Engineering Chemistry, Jain & Jain',
    notes: 'Corrosion occurs where oxygen concentration is lower (differential aeration).',
    order_index: 1,
  },
  {
    id: 'q3-2',
    subject_id: 'a1000000-0000-0000-0000-000000000003',
    question: 'Describe the process of electroplating with a suitable example.',
    answer: 'Electroplating deposits a thin layer of metal on an object using electrolysis. Example: Chrome plating - Object = cathode, CrO₃ solution = electrolyte. Cr⁶⁺ ions are reduced at cathode: Cr⁶⁺ + 6e⁻ → Cr. Factors: current density, temperature, concentration, and additives.',
    image_url: null,
    references: 'Modern Electroplating, Lowenheim',
    notes: 'Anode replenishes the metal ions in the electrolyte bath.',
    order_index: 2,
  },
  {
    id: 'q3-3',
    subject_id: 'a1000000-0000-0000-0000-000000000003',
    question: 'Explain the construction and working of a lithium-ion battery.',
    answer: 'A Li-ion battery consists of: Anode (graphite, LiC₆), Cathode (LiCoO₂), and organic electrolyte with Li salt. During discharge: Li⁺ ions move from anode to cathode through electrolyte. Charging reverses this. Cell voltage: ~3.7V. High energy density, low self-discharge.',
    image_url: null,
    references: 'Linden\'s Handbook of Batteries',
    notes: 'Overcharging can cause thermal runaway.',
    order_index: 3,
  },
  {
    id: 'q3-4',
    subject_id: 'a1000000-0000-0000-0000-000000000003',
    question: 'What are conducting polymers? Explain with examples.',
    answer: 'Conducting polymers are organic polymers that conduct electricity. Examples: Polyacetylene, Polyaniline (PANI), Polypyrrole. Conductivity arises from conjugated π-electron systems. Doping (oxidation/reduction) increases conductivity from insulator to metallic range (10⁻¹⁰ to 10⁵ S/cm).',
    image_url: null,
    references: 'Handbook of Conducting Polymers',
    notes: 'Noble Prize in Chemistry 2000 was awarded for this discovery.',
    order_index: 4,
  },
  {
    id: 'q3-5',
    subject_id: 'a1000000-0000-0000-0000-000000000003',
    question: 'Explain the phase rule and its application to the water system.',
    answer: 'Gibbs Phase Rule: F = C - P + 2, where F = degrees of freedom, C = components, P = phases. For water (C=1): At triple point (P=3): F=0 (invariant). Along curves (P=2): F=1 (univariant). In regions (P=1): F=2 (bivariant).',
    image_url: null,
    references: 'Physical Chemistry, Atkins',
    notes: 'Triple point of water is at 0.01°C and 4.58 mmHg.',
    order_index: 5,
  },

  // Computational Problem Solving
  {
    id: 'q4-1',
    subject_id: 'a1000000-0000-0000-0000-000000000004',
    question: 'Explain the concept of recursion with the Tower of Hanoi problem.',
    answer: 'Recursion is a technique where a function calls itself. Tower of Hanoi: Move n disks from source to destination using auxiliary peg. Algorithm: 1) Move n-1 disks from source to auxiliary, 2) Move nth disk from source to destination, 3) Move n-1 disks from auxiliary to destination. Time complexity: O(2ⁿ).',
    image_url: null,
    references: 'Introduction to Algorithms, CLRS',
    notes: 'Minimal moves needed for n disks is 2ⁿ - 1.',
    order_index: 1,
  },
  {
    id: 'q4-2',
    subject_id: 'a1000000-0000-0000-0000-000000000004',
    question: 'Compare and contrast linear search and binary search algorithms.',
    answer: 'Linear Search: Sequentially checks each element. Time: O(n). Works on unsorted arrays. Binary Search: Divides search interval in half repeatedly. Time: O(log n). Requires sorted array. Binary search is exponentially faster for large datasets.',
    image_url: null,
    references: 'Algorithms & Data Structures, Wirth',
    notes: 'Always sort the array before using binary search.',
    order_index: 2,
  },
  {
    id: 'q4-3',
    subject_id: 'a1000000-0000-0000-0000-000000000004',
    question: 'Explain sorting algorithms: Bubble Sort vs Quick Sort.',
    answer: 'Bubble Sort: Repeatedly swaps adjacent elements if in wrong order. Time: O(n²) avg/worst. Space: O(1). Stable. Quick Sort: Picks pivot, partitions array, recursively sorts. Time: O(n log n) avg, O(n²) worst. Space: O(log n). Not stable. Quick Sort is preferred for large datasets.',
    image_url: null,
    references: 'The Art of Computer Programming, Knuth',
    notes: 'Quick Sort uses divide and conquer paradigm.',
    order_index: 3,
  },
  {
    id: 'q4-4',
    subject_id: 'a1000000-0000-0000-0000-000000000004',
    question: 'Explain linked lists and their types with operations.',
    answer: 'Linked List: Linear data structure where elements (nodes) contain data and pointer to next node. Types: Singly (next only), Doubly (next + prev), Circular (last points to first). Operations: Insert (O(1) at head), Delete (O(1) at head), Search (O(n)), Traverse (O(n)).',
    image_url: null,
    references: 'Data Structures using C, Tenenbaum',
    notes: 'No contiguous memory allocation required, unlike arrays.',
    order_index: 4,
  },
  {
    id: 'q4-5',
    subject_id: 'a1000000-0000-0000-0000-000000000004',
    question: 'Describe stack and queue data structures with real-world applications.',
    answer: 'Stack: LIFO (Last In First Out). Operations: push, pop, peek. Applications: function calls, undo operations, expression evaluation. Queue: FIFO (First In First Out). Operations: enqueue, dequeue, front. Applications: scheduling, BFS, print queue. Both have O(1) for insert/delete.',
    image_url: null,
    references: 'CLRS, Chapter 10',
    notes: 'Can be implemented using arrays or linked lists.',
    order_index: 5,
  },

  // Digital Computer Electronics
  {
    id: 'q5-1',
    subject_id: 'a1000000-0000-0000-0000-000000000005',
    question: 'Explain Boolean algebra and its fundamental theorems.',
    answer: 'Boolean algebra deals with binary variables (0,1) and logic operations (AND, OR, NOT). Fundamental theorems: Identity (A+0=A, A·1=A), Complement (A+A\'=1, A·A\'=0), De Morgan\'s (A+B)\' = A\'·B\' and (A·B)\' = A\'+B\'. Used in digital circuit design.',
    image_url: null,
    references: 'Digital Design, Mano',
    notes: 'Simplifies complex logic expressions to reduce gate count.',
    order_index: 1,
  },
  {
    id: 'q5-2',
    subject_id: 'a1000000-0000-0000-0000-000000000005',
    question: 'Design a full adder circuit and explain its working.',
    answer: 'Full Adder adds three bits (A, B, Cin) producing Sum and Carry. Sum = A⊕B⊕Cin, Cout = AB + BCin + ACin. Can be built from two half adders and an OR gate. Truth table has 8 rows (2³ combinations).',
    image_url: null,
    references: 'Digital Computer Electronics, Malvino',
    notes: 'Cascaded to form parallel adders.',
    order_index: 2,
  },
  {
    id: 'q5-3',
    subject_id: 'a1000000-0000-0000-0000-000000000005',
    question: 'Explain flip-flops: SR, JK, D, and T types.',
    answer: 'SR: Set-Reset, invalid when S=R=1. JK: Universal flip-flop, toggles when J=K=1. D: Data flip-flop, Q follows D on clock edge. T: Toggle flip-flop, toggles on T=1. All are sequential circuits with memory capability.',
    image_url: null,
    references: 'Modern Digital Electronics, Jain',
    notes: 'JK flip-flop avoids the indeterminate state of SR.',
    order_index: 3,
  },
  {
    id: 'q5-4',
    subject_id: 'a1000000-0000-0000-0000-000000000005',
    question: 'Describe the architecture of an 8-bit microprocessor.',
    answer: 'An 8-bit microprocessor (e.g., 8085) contains: ALU (arithmetic/logic), Accumulator (8-bit register), General registers (B,C,D,E,H,L), Program Counter (16-bit), Stack Pointer (16-bit), Instruction Register, Control Unit. It processes 8 bits of data per operation.',
    image_url: null,
    references: 'Microprocessor Architecture, Gaonkar',
    notes: 'Operating frequency of 8085 is around 3 MHz.',
    order_index: 4,
  },
  {
    id: 'q5-5',
    subject_id: 'a1000000-0000-0000-0000-000000000005',
    question: 'Explain the concept of multiplexers and demultiplexers.',
    answer: 'Multiplexer (MUX): Selects one of many inputs and forwards to single output. 4:1 MUX has 4 inputs, 2 select lines, 1 output. Demultiplexer (DEMUX): Routes single input to one of many outputs. Used in data routing, communication systems, and memory addressing.',
    image_url: null,
    references: 'Mano, Chapter 4',
    notes: 'Also known as data selectors and data distributors.',
    order_index: 5,
  },

  // Tamils and Technology
  {
    id: 'q6-1',
    subject_id: 'a1000000-0000-0000-0000-000000000006',
    question: 'Discuss the contribution of ancient Tamils to metallurgy.',
    answer: 'Ancient Tamils were pioneers in iron and steel technology. The Wootz steel (Ukku) was produced in Tamil Nadu and exported globally. Sangam literature references iron smelting. The Kodumanal archaeological site reveals advanced metallurgical practices dating to 300 BCE.',
    image_url: null,
    references: 'History of Tamil Metallurgy',
    notes: 'Wootz steel was used to make the famous Damascus swords.',
    order_index: 1,
  },
  {
    id: 'q6-2',
    subject_id: 'a1000000-0000-0000-0000-000000000006',
    question: 'Explain the irrigation systems developed by ancient Tamils.',
    answer: 'Ancient Tamils developed sophisticated irrigation: Kallanai (Grand Anicut) built by Karikala Chola (~2nd century CE) on the Kaveri River is one of the oldest water-diversion structures still in use. They built tanks (Eri), channels, and sluice systems for agriculture.',
    image_url: null,
    references: 'Sangam Water Management Texts',
    notes: 'Kallanai is a marvel of ancient hydraulic engineering.',
    order_index: 2,
  },
  {
    id: 'q6-3',
    subject_id: 'a1000000-0000-0000-0000-000000000006',
    question: 'Describe the maritime technology and trade of ancient Tamils.',
    answer: 'Tamils were master seafarers. Sangam texts describe ship-building (Kalam), navigation using stars. They traded with Rome, Southeast Asia, and China. Musiri was a major port. Items traded: pepper, pearls, textiles. Evidence: Roman coins found in Tamil Nadu.',
    image_url: null,
    references: 'Maritime History of Coromandel Coast',
    notes: 'Chola navy was one of the strongest in ancient Asia.',
    order_index: 3,
  },
  {
    id: 'q6-4',
    subject_id: 'a1000000-0000-0000-0000-000000000006',
    question: 'Explain the role of Tamil in computing and digital technology.',
    answer: 'Tamil was one of the first Indian languages to have Unicode support (Tamil Unicode block: U+0B80-U+0BFF). Tamil99 keyboard layout is standard. INFITT (International Forum for Information Technology in Tamil) promotes Tamil computing. Tamil NLP research is growing rapidly.',
    image_url: null,
    references: 'INFITT Conference Proceedings',
    notes: 'First Tamil font was created in 1977.',
    order_index: 4,
  },
  {
    id: 'q6-5',
    subject_id: 'a1000000-0000-0000-0000-000000000006',
    question: 'Discuss the architectural achievements of Tamil civilizations.',
    answer: 'Tamil temple architecture evolved through Pallava (rock-cut: Mahabalipuram), Chola (structural: Brihadeeswarar Temple), and Pandya periods. Features: Dravidian style, gopurams, vimanas. The Brihadeeswarar Temple (1010 CE) uses an 80-ton capstone lifted without modern machinery.',
    image_url: null,
    references: 'Dravidian Architecture, Brown',
    notes: 'UNESCO World Heritage Site.',
    order_index: 5,
  },

  // Basics of Electronics Engineering
  {
    id: 'q8-1',
    subject_id: 'a1000000-0000-0000-0000-000000000008',
    question: 'Explain the working principle of a PN junction diode.',
    answer: 'A PN junction forms when P-type (holes majority) and N-type (electrons majority) semiconductors join. Depletion region forms at junction. Forward bias (P→+, N→-): reduces barrier, current flows. Reverse bias: widens depletion region, minimal current. Used in rectification.',
    image_url: null,
    references: 'Electronic Devices and Circuit Theory, Boylestad',
    notes: 'Silicon diode has threshold voltage of 0.7V.',
    order_index: 1,
  },
  {
    id: 'q8-2',
    subject_id: 'a1000000-0000-0000-0000-000000000008',
    question: 'Describe the characteristics and applications of BJT.',
    answer: 'BJT (Bipolar Junction Transistor): Three terminals - Base, Collector, Emitter. Types: NPN and PNP. Regions: Active (amplification), Saturation (switch ON), Cutoff (switch OFF). Current gain: β = I_C/I_B. Applications: amplifiers, switches, oscillators.',
    image_url: null,
    references: 'Integrated Electronics, Millman & Halkias',
    notes: 'NPN is preferred over PNP due to higher mobility of electrons.',
    order_index: 2,
  },
  {
    id: 'q8-3',
    subject_id: 'a1000000-0000-0000-0000-000000000008',
    question: 'Explain operational amplifier characteristics and applications.',
    answer: 'Op-Amp: High gain differential amplifier. Ideal characteristics: infinite gain, infinite input impedance, zero output impedance, infinite bandwidth. Applications: Inverting amplifier (gain=-Rf/Ri), Non-inverting (gain=1+Rf/Ri), Summing amplifier, Integrator, Differentiator.',
    image_url: null,
    references: 'Op-Amps and Linear Integrated Circuits, Gayakwad',
    notes: 'IC 741 is a popular general-purpose op-amp.',
    order_index: 3,
  },
  {
    id: 'q8-4',
    subject_id: 'a1000000-0000-0000-0000-000000000008',
    question: 'Compare MOSFET and JFET transistors.',
    answer: 'JFET: Voltage-controlled, depletion mode only, gate is reverse-biased PN junction. MOSFET: Voltage-controlled, enhancement and depletion modes, gate insulated by oxide layer. MOSFET advantages: higher input impedance, easier fabrication, used in CMOS logic.',
    image_url: null,
    references: 'Boylestad, Chapter 6',
    notes: 'MOSFET gate input resistance is extremely high (>10¹² ohms).',
    order_index: 4,
  },
  {
    id: 'q8-5',
    subject_id: 'a1000000-0000-0000-0000-000000000008',
    question: 'Explain rectifier circuits: half-wave and full-wave.',
    answer: 'Half-wave: Uses single diode, conducts only positive half cycles. Efficiency: 40.6%, ripple factor: 1.21. Full-wave (bridge): Uses 4 diodes, conducts both halves. Efficiency: 81.2%, ripple factor: 0.48. Filter capacitor smooths output DC.',
    image_url: null,
    references: 'Millman & Halkias, Chapter 4',
    notes: 'Bridge rectifier does not require a center-tapped transformer.',
    order_index: 5,
  },
];
